### ISSUE TITLE
Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by eunjin0212** [eunjin0212/React-Study#1]
npm start

> react-study@1.0.0 start C:\Users\eunji\OneDrive\Documents\dev\React-Study
> webpack-dev-server

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\eunji\OneDrive\Documents\dev\React-Study\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)      
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\eunji\OneDrive\Documents\dev\React-Study\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)        
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)      
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\eunji\\OneDrive\\Documents\\dev\\React-Study\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-study@1.0.0 start: `webpack-dev-server`
npm ERR!
npm ERR! Failed at the react-study@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.        

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eunji\AppData\Roaming\npm-cache\_logs\2020-10-29T09_45_30_098Z-debug.log

**Comment by eunjin0212** [comment]
solved this problem
```
"scripts": {
    "dev": " webpack serve --env development"
  },
```
add `package.json`
and `npm run dev`
